"""initial schema

Revision ID: 67d3c1f9c6a2
Revises: 
Create Date: 2026-08-24 20:46:04.793457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67d3c1f9c6a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', postgresql.ENUM('TRIAGE', 'PLAN_CREATED', 'SUPPRESSION', 'ACTION_SCHEDULED', 'ACTION_EXECUTED', 'ACTION_OUTCOME', 'CONFIG_CHANGE', name='ledger_event_type'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_ledger_merchant_id'), 'audit_ledger', ['merchant_id'], unique=False)
    op.create_index('ix_ledger_created', 'audit_ledger', ['created_at'], unique=False)
    op.create_index('ix_ledger_entity', 'audit_ledger', ['entity_type', 'entity_id'], unique=False)
    op.create_table('config_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_window_hours', sa.Integer(), nullable=False),
    sa.Column('max_contacts', sa.Integer(), nullable=False),
    sa.Column('contact_cooldown_hours', sa.Integer(), nullable=False),
    sa.Column('uplift_threshold', sa.Float(), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('expire_after_days', sa.Integer(), nullable=False),
    sa.Column('kill_switch', sa.Boolean(), nullable=False),
    sa.Column('policy_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'version', name='uq_merchant_config_version')
    )
    op.create_index(op.f('ix_config_versions_merchant_id'), 'config_versions', ['merchant_id'], unique=False)
    op.create_table('failure_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('gateway_event_id', sa.String(length=128), nullable=False),
    sa.Column('transaction_id', sa.String(length=128), nullable=False),
    sa.Column('subscription_id', sa.String(length=128), nullable=True),
    sa.Column('customer_id', sa.String(length=128), nullable=False),
    sa.Column('customer_email', sa.String(length=256), nullable=True),
    sa.Column('instrument_type', postgresql.ENUM('CARD', 'UPI', 'EMANDATE', 'NETBANKING', 'WALLET', name='instrument_type'), nullable=False),
    sa.Column('instrument_token', sa.String(length=256), nullable=False),
    sa.Column('raw_error_code', sa.String(length=64), nullable=False),
    sa.Column('raw_error_description', sa.Text(), nullable=True),
    sa.Column('normalized_code', sa.String(length=64), nullable=False),
    sa.Column('failure_class', postgresql.ENUM('HARD', 'SOFT', 'MANDATE', 'UNKNOWN', name='failure_class'), nullable=True),
    sa.Column('classification_source', sa.String(length=32), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'gateway_event_id', name='uq_merchant_gateway_event')
    )
    op.create_index('ix_failure_class', 'failure_events', ['failure_class'], unique=False)
    op.create_index(op.f('ix_failure_events_customer_id'), 'failure_events', ['customer_id'], unique=False)
    op.create_index(op.f('ix_failure_events_merchant_id'), 'failure_events', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_failure_events_transaction_id'), 'failure_events', ['transaction_id'], unique=False)
    op.create_table('recovery_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('failure_event_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('plan_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['failure_event_id'], ['failure_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('failure_event_id')
    )
    op.create_index(op.f('ix_recovery_plans_merchant_id'), 'recovery_plans', ['merchant_id'], unique=False)
    op.create_table('suppressions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('failure_event_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('action_type', postgresql.ENUM('RETRY', 'CONTACT_EMAIL', 'REAUTH_REQUEST', 'ESCALATE_HUMAN', name='action_type'), nullable=False),
    sa.Column('rule_name', sa.String(length=128), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['failure_event_id'], ['failure_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppressions_merchant_id'), 'suppressions', ['merchant_id'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('failure_event_id', sa.UUID(), nullable=False),
    sa.Column('recovery_plan_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('action_type', postgresql.ENUM('RETRY', 'CONTACT_EMAIL', 'REAUTH_REQUEST', 'ESCALATE_HUMAN', name='action_type'), nullable=False),
    sa.Column('status', postgresql.ENUM('SCHEDULED', 'EXECUTING', 'SUCCEEDED', 'FAILED', 'SUPPRESSED', 'UNRESOLVED', name='action_status'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.JSON(), nullable=True),
    sa.Column('retry_number', sa.Integer(), nullable=True),
    sa.Column('estimated_success_prob', sa.Float(), nullable=True),
    sa.Column('estimated_uplift', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['failure_event_id'], ['failure_events.id'], ),
    sa.ForeignKeyConstraint(['recovery_plan_id'], ['recovery_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_action_scheduled', 'actions', ['scheduled_at'], unique=False)
    op.create_index('ix_action_status', 'actions', ['status'], unique=False)
    op.create_index(op.f('ix_actions_merchant_id'), 'actions', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_actions_merchant_id'), table_name='actions')
    op.drop_index('ix_action_status', table_name='actions')
    op.drop_index('ix_action_scheduled', table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_suppressions_merchant_id'), table_name='suppressions')
    op.drop_table('suppressions')
    op.drop_index(op.f('ix_recovery_plans_merchant_id'), table_name='recovery_plans')
    op.drop_table('recovery_plans')
    op.drop_index(op.f('ix_failure_events_transaction_id'), table_name='failure_events')
    op.drop_index(op.f('ix_failure_events_merchant_id'), table_name='failure_events')
    op.drop_index(op.f('ix_failure_events_customer_id'), table_name='failure_events')
    op.drop_index('ix_failure_class', table_name='failure_events')
    op.drop_table('failure_events')
    op.drop_index(op.f('ix_config_versions_merchant_id'), table_name='config_versions')
    op.drop_table('config_versions')
    op.drop_index('ix_ledger_entity', table_name='audit_ledger')
    op.drop_index('ix_ledger_created', table_name='audit_ledger')
    op.drop_index(op.f('ix_audit_ledger_merchant_id'), table_name='audit_ledger')
    op.drop_table('audit_ledger')
    # ### end Alembic commands ###
